news:
  # Note: These topics are optional - the prompt template below will guide the news selection
  topics:
    - "Technical breakthroughs and research developments"
    - "Product launches and major updates"
    - "Policies, regulations, and governance"
    - "Funding rounds and investments"
    - "Industry applications and case studies"

  prompt_template: |
      Please search and summarize 10 recent AI-related news items with the following requirements:
      1. Cover both international and domestic news, maintaining balance between the two
      2. News should be recent (within the past few weeks to months)
      3. Include multiple dimensions: technical breakthroughs, product launches, policies and regulations, funding rounds, industry applications, etc.
      4. For each news item include:
         - A concise headline
         - Core content summary (2-3 sentences)
         - Citation from reliable sources
      5. Present organized by international and domestic categories
      6. Use clear and concise language suitable for quick scanning

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
