news:
  # Note: These topics are optional - the prompt template below will guide the news selection
  topics:
    - "Technical breakthroughs and research developments"
    - "Product launches and major updates"
    - "Policies, regulations, and governance"
    - "Funding rounds and investments"
    - "Industry applications and case studies"

  prompt_template: |
      Please generate a comprehensive AI news digest with 10 recent news items following these requirements:

      1. **Use the web_search tool** to find the most current AI news from 2025 (not from your training data)
      2. Cover both international and domestic news, maintaining balance between the two
      3. Search for multiple dimensions:
         - Technical breakthroughs and research developments
         - Product launches and major updates
         - Policies, regulations, and governance
         - Funding rounds and investments
         - Industry applications and case studies

      4. For each news item include:
         - A concise headline
         - Core content summary (2-3 sentences)
         - Source citation from your search results

      5. Present organized by:
         - International News (5 items)
         - Domestic News (5 items)

      6. Use clear and concise language suitable for quick scanning

      Focus on these topics:
      {topics}

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
