news:
  # Enable fetching real-time news from RSS feeds (recommended)
  # Set to false to use AI-generated news based on AI's knowledge (may be outdated)
  use_real_sources: true

  # Enable web search tool (uses DuckDuckGo API via Claude tool calling)
  # Note: DuckDuckGo API often returns limited results. RSS feeds (use_real_sources) is more reliable.
  enable_web_search: false

  # Include Chinese news sources
  include_chinese_sources: true

  # Maximum news items to fetch per source
  max_items_per_source: 5

  # Note: These topics are optional - the prompt template below will guide the news selection
  topics:
    - "Technical breakthroughs and research developments"
    - "Product launches and major updates"
    - "Policies, regulations, and governance"
    - "Funding rounds and investments"
    - "Industry applications and case studies"

  prompt_template: |
      Please summarize and organize the recent AI news items into a well-structured digest with the following requirements:
      1. Group news by categories (e.g., Technical Breakthroughs, Product Launches, Policies & Regulations, Funding & Investment, Industry Applications)
      2. For each news item include:
         - A clear, concise headline
         - Key points summary (2-3 sentences)
         - Source attribution
      3. Prioritize the most significant and recent developments
      4. Use clear markdown formatting for easy reading
      5. Maintain a professional and informative tone
      6. If the news is in English but the output language is Chinese, translate appropriately while keeping technical terms accurate

      Focus on these topics:
      {topics}

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
