name: Daily AI News Digest

on:
  # Run daily at 9:00 AM UTC (adjust as needed)
  schedule:
    - cron: '0 0 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate and send AI news digest
        env:
          # Anthropic API Key (required)
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

          # Email configuration (optional)
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}

          # Webhook configuration (optional)
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

          # Notification methods (comma-separated: email,webhook)
          NOTIFICATION_METHODS: ${{ secrets.NOTIFICATION_METHODS }}

          # Language configuration (optional, defaults to 'en')
          AI_RESPONSE_LANGUAGE: ${{ secrets.AI_RESPONSE_LANGUAGE }}

        run: |
          python main.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
          retention-days: 7
