name: Daily AI News Digest

on:
  # Run daily at 0:00 AM UTC (adjust as needed)
  schedule:
    - cron: "0 0 * * *"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  generate-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate and send AI news digest
        env:
          # All values come from GitHub Repository Secrets
          # Configure at: Settings → Secrets and variables → Actions → Repository secrets

          # Required Secrets
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          NOTIFICATION_METHODS: ${{ secrets.NOTIFICATION_METHODS }}

          # Optional: Email via Resend.com
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}

          # Optional: Webhook
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

          # Optional: Language (defaults to 'en' if not set)
          AI_RESPONSE_LANGUAGE: ${{ secrets.AI_RESPONSE_LANGUAGE }}

        run: |
          python main.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-logs
          path: |
            *.log
          retention-days: 7
